### ISSUE TITLE
Can't edit / delete records on models with custom set_primary_key

### ISSUE THREAD

**Issue by igrigorik** [neerajsingh0101/admin_data#13]
Hey guys, love the plugin. Just dropped it into one of my projects and it looks like any model that overrides the primary key (have a hash key for example, instead of straight up ID), the key is not linked from the list view, or from anywhere else for that matter.

(hope I'm not doing something silly).

ig

**Comment by neerajsingh0101** [comment]
Hi llya,

I have never heard of overriding the primary key. Can you quickly provide me a an example of a model so that I could better understand the situation.  I could not follow your hash key example.

**Comment by igrigorik** [comment]
Hmm, looks like it's something else. Just setup a skeleton rails app with a custom primary key and it appears to work just fine. That's not it. Investigating..

As far as the model goes:

script/generate model Widgets widget_hash:string body:string

class Widgets < ActiveRecord::Base
  set_primary_key :widget_hash
end

**Comment by neerajsingh0101** [comment]
admin_data works for custom primary key. Add a test for this one and all the tests are passing. Closing this issue.
