### ISSUE TITLE
How To Handle Model In Module?

### ISSUE THREAD

**Issue by mikegrassotti** [neerajsingh0101/admin_data#2]
Excellent plugin! It works great for all of my models except those that are namespaced inside modules. For example: 

class Email::Message < ActiveRecord::Base
  self.table_name="email_messages"
  belongs_to :user, :class_name => "User"
end

When I attempt to access records in this model via the admin interface, I see the following in my server logs:

Processing AdminData::MainController#list (for 127.0.0.1 at 2009-08-26 22:10:45) [GET]
  Parameters: {"klass"=>"Email::Message", "action"=>"list", "controller"=>"admin_data/main"}
Redirected to http://localhost:3000/admin_data
Filter chain halted as [:get_class_from_params] rendered_or_redirected.
Completed in 2ms (DB: 0) | 302 Found [http://localhost/admin_data/list?klass=Email%3A%3AMessage]
controller_name is main

And ideas?

**Comment by neerajsingh0101** [comment]
I'll take a look. Thanks for feedback.

**Comment by neerajsingh0101** [comment]
Can you try with the latest version of this plugin. Just now I pushed changes that support namespaced models.

**Comment by neerajsingh0101** [comment]
Verified that the current solution works with namespaced model. Closing this issue.
