### ISSUE TITLE
Patch to allows update of protected attributes

### ISSUE THREAD

**Issue by Florent2** [neerajsingh0101/admin_data#22]
Hello,

Currently admin_data does not update protected attributes. However I find useful to be able to update also protected attributes in the admin area. Here is a patch to permit the update of protected attributes:
http://gist.github.com/254595

I tested by hand on my application, and the patch works, protected attributes can be updated.

Unfortunately the test I wrote does not work:
    should_change "@article.status", :from => 'published', :to => 'something'
I am not sure why, as I usually do not use shoulda, but any help/indication/suggestion would be welcome so that I can fix the test :)

And thanks for the plugin, it is very useful!

**Comment by neerajsingh0101** [comment]
If an attribute has been made protected, then it was done for a reason. I do not feel very comfortable updating attributes without providing any indication to the user that protected attributes might get updated.

Closing this issue for now. Might take up later.

**Comment by Florent2** [comment]
Thanks for your answer Neeraj.

Would be acceptable for you a configuration attribute "allow_protected_attributes_update"? 
Update of protected attributes would work only when this attribute is true, its default value would be false.

Additionnaly in the user interface, a warning sign could be added for protected attributes.
