### ISSUE TITLE
working with HABTM models

### ISSUE THREAD

**Issue by silkcom** [neerajsingh0101/admin_data#24]
I'd like to see the ability to work with has and belongs to many models.  A multiselect list or add/remove interface or something like that.

**Comment by neerajsingh0101** [comment]
HABTM is slowly falling of favor. It will not be supported. Thanks

**Comment by silkcom** [comment]
too bad, have to look elsewhere

**Comment by neerajsingh0101** [comment]
Too much work is the main reason. I would rather spend that time on working on other features. Sorry.
