### ISSUE TITLE
Problem with advance search, fails with NZKoz-rails_xss plugin

### ISSUE THREAD

**Issue by ghost** [neerajsingh0101/admin_data#25]
When I use the advance search feature I always get the following error. Rendering /home/family/Desktop/old/final2/vendor/plugins/admin_data/app/views/admin_data/search/search/_listing.html.erb

ArgumentError (wrong number of arguments (1 for 2)):
  vendor/plugins/admin_data/app/controllers/admin_data/search_controller.rb:55:in `advance_search'
  vendor/plugins/admin_data/app/controllers/admin_data/search_controller.rb:44:in`advance_search

I using rails 2.3.5. 

Also, i noticed that this plugin will not work with the new rails_xss plugin

**Comment by neerajsingh0101** [comment]
I will look into this issue. All of my projects are using 2.3.4 so I never tested this plugin with Rails 2.3.5 along with rails_xss plugin.

**Comment by neerajsingh0101** [comment]
should be fixed in a few weeks

**Comment by neerajsingh0101** [comment]
It has been fixed in master. Tested with rails 2.3.8 and rails_xss plugin for 2.3.8
