### ISSUE TITLE
If you have a table named feeds it chooses the wrong route.

### ISSUE THREAD

**Issue by thebaldwin** [neerajsingh0101/admin_data#26]
I have a table called feeds.

There's a route you have for /feed/:klass so it doesn't use the /:klass/search route when I query for /feed/search.

**Comment by neerajsingh0101** [comment]
That's not good. I will think of a way to avoid name collision. Will let you know when this issue is fixed.

**Comment by neerajsingh0101** [comment]
It should be fixed now. Try getting the latest version of plugin and lemme know how it goes.

**Comment by neerajsingh0101** [comment]
closing it. If you still have an issue then lemme know.
