### ISSUE TITLE
ruby 1.9.1 compatibility

### ISSUE THREAD

**Issue by mhinton** [neerajsingh0101/admin_data#28]
When using ruby 1.9.1 if a table has data in it I get the following error message.

Showing vendor/plugins/admin_data/app/views/admin_data/search/search/_listing.html.erb where line #31 raised:

undefined method `name' for nil:NilClass

This works fine when the table is empty.

**Comment by chrisvariety** [comment]
I've fixed this in my branch.

**Comment by neerajsingh0101** [comment]
Fix by chrismcc has been merged. 

Closing this issue. If you still have an issue then please open a new ticket.
