### ISSUE TITLE
raise errors when rake db:create

### ISSUE THREAD

**Issue by zhaorong** [neerajsingh0101/admin_data#29]
$ rake db:create --trace

error messages:
...............
/home/zhaorong/NetBeansProjects/clubchloe/vendor/plugins/admin_data/lib/admin_data/settings.rb:26:in `set='
/home/zhaorong/NetBeansProjects/clubchloe/vendor/plugins/admin_data/lib/admin_data/settings.rb:30:in`initialize_defaults'
/home/zhaorong/NetBeansProjects/clubchloe/vendor/plugins/admin_data/init.rb:43:in `evaluate_init_rb'
..............

```
    If I remove admin_data plugin, rake db:create command is works.
```

**Comment by neerajsingh0101** [comment]
what version of rails you are using? I am not able to produce this case.

This is what I did . http://gist.github.com/286893
And it is not failing.

Can you try with latest plugin version?

Thanks

**Comment by neerajsingh0101** [comment]
closing it
