### ISSUE TITLE
Serialized arrays

### ISSUE THREAD

**Issue by endofunky** [neerajsingh0101/admin_data#3]
I am currently using a serialized array which is stored as a string in the database to handle roles in my user model. Unfortunately though, admin_data tries to call mb_chars on that Array object.

Errors follow:

Showing vendor/plugins/admin_data/app/views/admin_data/main/list.html.erb where line #33 raised: 

<pre>
undefined method `mb_chars' for ["admin"]:Array
</pre>

Extracted source (around line #33): 

<pre>
30: 
31:         <div class="block" id="block-tables">
32:           <div class="content">          
33:             <%= erb_file('search','_search_results.html.erb') %>
34:           </div>
35:         </div>
36: 
</pre>

**Comment by neerajsingh0101** [comment]
I will take a look and will make truncate method conditional

**Comment by neerajsingh0101** [comment]
I stored varities of arryay after marshalling  them. On truncate  I was getting weird characters but I never got exception.

Anyway, I have but the truncate call inside a begin rescue block. Source code has been updated. Can you give the latest code a try and let me know if this solves your problem.

**Comment by endofunky** [comment]
It works great. Good job!

**Comment by neerajsingh0101** [comment]
cool. closing this issue.
