### ISSUE TITLE
handling large has_one associations

### ISSUE THREAD

**Issue by igrigorik** [neerajsingh0101/admin_data#31]
We have a production app on which we want to use admin_data, but running into a problem.. The tables are medium-sized (30-50K rows), and when we hit "create record", admin_data is trying to create a dropdown with all of those users, which results in 50s load times + a very heavy page that freezes anytime you touch that dropdown. ;-)

Not sure how to handle this, but intuitively, 30-50k rows is not that big, and I think there should be some way to override the settings and not generate that drop down (i'm perfectly ok with a simple input box). Perhaps there is a better way to handle this?

**Comment by neerajsingh0101** [comment]
First thought that comes to my mind is that there should be a way to override the setting so that , as you suggested, app displays an input field instead of a drop down.

I will look into it this weekend.

**Comment by neerajsingh0101** [comment]
Fixed in master http://github.com/neerajdotname/admin_data/commit/f7d5c5c8220803d0eca1d76c7c7de219fd34ecdc 

Also look at documentation http://neerajdotname.github.com/admin_data/#override_drop_down_associations

Lemme know if it works out or not.

**Comment by igrigorik** [comment]
Works as advertised, good stuff!
