### ISSUE TITLE
maxlength on an integer field set at 4?

### ISSUE THREAD

**Issue by igrigorik** [neerajsingh0101/admin_data#32]
<pre>| col_id    | int(11)      | NO   |     | NULL    |                |</pre>

But, for some reason, the input box that's showing up is limited to 4 chars?

**Comment by neerajsingh0101** [comment]
That's not good. Will look into it.

**Comment by neerajsingh0101** [comment]
What database you are using?

Also can you check what you get  when in script/console you invoke limit method on that column. In this case I am invoking limit method on column age for users table.

User.columns.find{|r| r.name == 'age'}.limit
=> 2

**Comment by igrigorik** [comment]
> > Role.columns.find{|r| r.name == 'user_id'}.limit
> > => 4
> > Role.columns.find{|r| r.name == 'user_id'}.sql_type
> > => "int(11)"

Seems to be a somewhat relevant discussion:
https://rails.lighthouseapp.com/projects/8994/tickets/876

**Comment by neerajsingh0101** [comment]
http://github.com/neerajdotname/admin_data/commit/4776ce660c6cf0e44d18695bb143423096349398

http://neerajdotname.github.com/admin_data/#ignore_column_limit

Hope that helps.

**Comment by igrigorik** [comment]
Works great, thanks!
