### ISSUE TITLE
"rake  admin_data:localize_views" fails

### ISSUE THREAD

**Issue by waugh** [neerajsingh0101/admin_data#33]
no such file to load -- vendor/plugins/admin_data/tasks/../lib/admin_data/admin_data_tasks

**Comment by alexrothenberg** [comment]
It looks like the contents of this file were deleted in on January 28, 2010 http://github.com/neerajdotname/admin_data/commit/e42e72b97541e9d9b5f16992b437f41ea91a6dde#diff-22 and the file itself went away January 31 http://github.com/neerajdotname/admin_data/commit/8ad3521601ee582e8807b830ebea9492d43d729a.

I created the file last year for the "localize_views" functionality but am not sure if Neeraj wants to continue supporting that.

--alex

**Comment by neerajsingh0101** [comment]
rake task admin_data:localize_views is gone and is not supported. If there is enough demand I can do theme support. As of now closing this ticket.
