### ISSUE TITLE
Routing Error on Delete

### ISSUE THREAD

**Issue by lostmahbles** [neerajsingh0101/admin_data#46]
Hi I'm having trouble using the delete (and destroy) actions on my models.  I get the following error:

Routing Error

No route matches "/admin_data/klass/xxxx/7/del"

Where xxxx is the model class name and 7 is the ID.

I'm running Rails 3.0.0.

Any suggestions?

**Comment by neerajsingh0101** [comment]
I am looking into this issue.

**Comment by neerajsingh0101** [comment]
Can you try with v 1.0.10 of admin_data. This bug should be fixed there. Please do report back if that version fixes your problem.

Thanks

**Comment by lostmahbles** [comment]
That fixed it, thanks!
