### ISSUE TITLE
Load models in plugins

### ISSUE THREAD

**Issue by pacoguzman** [neerajsingh0101/admin_data#5]
Hi!

This plugin is awesome! very awesome I think.

But know I'm building an application that use desert to load some plugins you can see it here http://github.com/pacoguzman/tog_with_cukes and I think that admin_data doesn't load the models specified in plugins. Could be posible to add these models to admin_data interface?

Thanks in advance

**Comment by neerajsingh0101** [comment]
I see. Once I worked on a project where the model was in a plugin. Currently I am not working on any such project and hence I did not implement it.

Lemme think about it. I will keep this issue open and will apply the fix sometime soon.

I am glad that you like the plugin. Thanks for the feedback.

**Comment by neerajsingh0101** [comment]
Closing this issue. Deferring this one. May be I'll take up later.
