### ISSUE TITLE
Error when using with Devise

### ISSUE THREAD

**Issue by dadamsuk** [neerajsingh0101/admin_data#51]
I'm on Rails 3 and using Devise for authentication.

I've installed admin_data as per the install instructions but when I browse /admin_data I get this error:

```
  Started GET "/admin_data" for x.x.x.x at Fri Oct 22 16:03:54 +0100 2010
Processing by AdminData::MainController#all_models as HTML
 Rendered text template (0.0ms)
 Completed 401 Unauthorized in 12ms (Views: 1.3ms | ActiveRecord: 1.7ms)

   NoMethodError (undefined method `new__session_path' for #<Devise::FailureApp:0x2aaab49be0b8>):
```

In an attempt to workaround this I have temporarily used:

```
  AdminData::Config.set = {
    :is_allowed_to_view => true,
    :is_allowed_to_update =>true
 }
```

but even so it croaks with the above.  I assume this is something to do with a form that admin_data is trying to render, which is trying to used a named route URL, but I am not sure how to fix it.

Thanks.

**Comment by neerajsingh0101** [comment]
looks like devise is messing things up for admin_data. I will look into it tonight and will update you. thanks.

**Comment by dadamsuk** [comment]
Excellent.  Let me know if you need any more debug info from me.

**Comment by neerajsingh0101** [comment]
Not sure why it is not working for you. Just now I tested admin_data with a project which has routes like this. http://pastie.org/1241322

This project uses devise. 

When I visit http://localhost:3000/admin_data everything works fine for me.

Can run bundle update admin_data and then bundle update devise to ensure that you are latest released version of both the gems which is what I am using.

**Comment by dadamsuk** [comment]
Tried that, no change.  Any other ideas?  I really appreciate the help and would love to get this working.

Here is my complete list:
- abstract (1.0.0)
- actionmailer (3.0.0)
- actionpack (3.0.0)
- activemodel (3.0.0)
- activerecord (3.0.0)
- activeresource (3.0.0)
- activesupport (3.0.0)
- admin_data (1.0.1)
- arel (1.0.1)
- bcrypt-ruby (2.1.2)
- builder (2.1.2)
- bundler (1.0.3)
- columnize (0.3.1)
- crack (0.1.8)
- date_validator (0.5.9)
- devise (1.1.3)
- erubis (2.6.6)
- fastercsv (1.5.3)
- formtastic (1.1.0)
- geokit (1.5.0)
- i18n (0.4.1)
- linecache (0.43)
- mail (2.2.7)
- mime-types (1.16)
- mysql (2.8.1)
- nokogiri (1.4.3.1)
- polyglot (0.3.1)
- rack (1.2.1)
- rack-mount (0.6.13)
- rack-test (0.5.6)
- rails (3.0.0)
- railties (3.0.0)
- rake (0.8.7)
- ruby-debug (0.10.3)
- ruby-debug-base (0.10.3)
- savon (0.7.9)
- thor (0.14.3)
- treetop (1.4.8)
- tzinfo (0.3.23)
- warden (0.10.7)
- will_paginate (2.3.15)
- ym4r (0.6.1)

**Comment by neerajsingh0101** [comment]
Can you post your Gemfile. May be the order matters.

Also in order to debug can you clone your project. Delete all controllers except ApplicationController, all models and views, keep routes and then open source that project so that I can take a look.

Or if it is okay then you can add me as collaborator in the project. I would really like to get this problem solved.

Devise is a popular gem and I am sure others might run into same issue.

**Comment by dadamsuk** [comment]
I've just created a brand new Rails 3 project, added Devise and admin_auto and it works perfectly.  I am going to look back at my original app and strip some bits out until it starts working, hopefully before I get back to the point of a brand new empty app.  I'll let you know when I discover the culprit, but for now, it looks like Devise and admin_auto are fine in one app.

**Comment by neerajsingh0101** [comment]
Good luck in hunting it down. Sometimes it requires patience :-)

If I could be of any assistance then do let me know.

Thanks.

**Comment by dadamsuk** [comment]
Some progress:

It works in development mode, but not in production.  I have tried on both the local instance of my app (in development mode: works), and on my server instance (in production mode: doesn't work).  Then I switched my server instance to development mode and it works.  Finally I took my brand new, bare bones, simple test app and tried it in development mode (works) and production mode (doesn't work).  So it's pretty conclusive I think.  

Any ideas?

By the way, now I've seen it in action, I think it's excellent and would love to use it.  I was keen to see if it was okay with some of my slightly larger tables (28 million rows) and it was fine.  So, well done for that.

**Comment by neerajsingh0101** [comment]
I am happy to know that it works with 28 million rows. I have only 4000 records in my production database. :-)

It worked for me in production mode with devise.

Can you put your barebone app on github which does not work in production mode?

**Comment by neerajsingh0101** [comment]
In case someone else is having the same problem:

If you are experiencing problem with devise then make sure that you are using version "1.0.16" of admin_data.

gem 'admin_data', ''>= 1.0.16'

**Comment by dadamsuk** [comment]
I can confirm that the above fix does work.  Thanks for all your help.
