### ISSUE TITLE
Admin config in initializer does nothing?

### ISSUE THREAD

**Issue by waynehoover** [neerajsingh0101/admin_data#52]
I'm using devise and put this in a initializers/adimn_data.rb

```
AdminData::Config.set = {
    :is_allowed_to_view => lambda {|controller| controller.send('user_signed_in?') },
    :is_allowed_to_update => lambda {|controller| controller.send('user_signed_in?')},
}     
```

yet even when I'm signed out I can still access admin_data what am I doing wrong? or is this a bug?

**Comment by neerajsingh0101** [comment]
I have updated the wiki to answer your question. Please see the very first line.

https://github.com/neerajdotname/admin_data/wiki/Security-Configuration

And thanks for reporting.

If you have any question then let me know.

**Comment by neerajsingh0101** [comment]
I am assuming that you are using development environment. If this is happening in production then it is a bug?

**Comment by waynehoover** [comment]
No this is happening in development. Is there any way to test this in development?

**Comment by nsinghonyx** [comment]
In development you can't turn that off. In development mode no security is enforced.
