### ISSUE TITLE
Give admin_data routes priority over my own catch-all vanity url route?

### ISSUE THREAD

**Issue by kgit** [neerajsingh0101/admin_data#55]
My app allows users to create a username that will give them a vanity url. For example, bob can view his main page at:
http://example.com/bob

To support this, I have a catch-all route at the bottom of my routes.rb file:
get ':username' => 'users#show'

This prevents me from accessing /admin_data, because my app tries to interpret admin_data as a username.

Is there any way for me to give the admin_data gem's routes priority over my catch-all route?  I tried copying all the routes from admin_data/config/routes.rb into my own routes.rb file, but that gives me this error when viewing /admin_data:
The action 'index' could not be found for AdminData::MainController

I am using rails 3.0.3.

I'm new at this github thing, so feel free to yell at me if this is the wrong way to ask a question :)

**Comment by neerajsingh0101** [comment]
I have not tested it but following should work. Lemme know if it works for you or not so that I could document it.

```
match '/admin_data', :to => 'admin_data/main#all_models'
```

Also make sure that you are using latest version of admin_data by running

```
bundle update admin_data
```

**Comment by kgit** [comment]
Yes, this works!  Thanks!

**Comment by neerajsingh0101** [comment]
Awesome. I will add it to documentation.
