### ISSUE TITLE
[security] public#serv

### ISSUE THREAD

**Issue by comboy** [neerajsingh0101/admin_data#57]
There seems to be a security hole in public#serv
1. It will serve files to unauthorized users, which I think is bad, I don't think that application user should be able to even know that I am using admin_data. But that's not really high priority.
2. More worrying is that silent assumption in the current code that I am willing to share all files from my hard drive that end up with js or css. That includes .rjs in my app , and all apps on the server. 

Suggested patch:
https://github.com/comboy/admin_data/commit/cb2a31972cf679755d9a4d09c449b972726e09dc

**Comment by neerajsingh0101** [comment]
applied. closing the ticket.
