### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by 29decibel** [neerajsingh0101/admin_data#60]
Instead of

AdminData::Config.set = {
 :find_conditions => ....
}

Now you need to do

AdminData.config do |config|
 config.find_conditions = ...
}

the last line should be "end" instead of "}"

**Comment by neerajsingh0101** [comment]
Fixed in new release. https://github.com/neerajdotname/admin_data/commit/37eaaac4b60bf0168778f7832a132810da0902c4

Thanks for reporting.
