### ISSUE TITLE
FormHelper broken for Records with Associations

### ISSUE THREAD

**Issue by jpshackelford** [neerajsingh0101/admin_data#61]
When attempting to create a new record for a model with associations I get the following error:

undefined method `[]' for true:TrueClass at
admin_data (1.1.8) app/helpers/admin_data/application_helper.rb:151:in`form_field'

See https://github.com/neerajdotname/admin_data/blob/master/app/helpers/admin_data/application_helper.rb#L151

It looks like the problem is that config.drop_down_for_associations is actually a boolean not a hash. It is initialized as a boolean at: https://github.com/neerajdotname/admin_data/blob/master/lib/admin_data/configuration.rb#L105

The configuration documentation also suggests that this should be a boolean not a hash. See
https://github.com/neerajdotname/admin_data/wiki/Customizing-admin_data-for-a-Rails-3-application

**Comment by jpshackelford** [comment]
I now see that in the tests, config.drop_down_for_associations is set to a hash:

https://github.com/neerajdotname/admin_data/blob/master/test/rails_root/config/initializers/admin_data.rb#L16

When I comment the line out and run the tests a single scenario breaks with the same stacktrace as I was seeing in my app.

So if this is the desired functionality probably the constructor just needs to change to initialize with an empty Hash, and the doc reference above should be updated to reflect that.

**Comment by neerajsingh0101** [comment]
I think this is fixed now. Right.

**Comment by jpshackelford** [comment]
Fixed as of https://github.com/neerajdotname/admin_data/commit/f561bf0d6a6341feac21e28dfd4ef7a16575154c
