### ISSUE TITLE
RoutingError due to redefined route

### ISSUE THREAD

**Issue by axs89** [neerajsingh0101/admin_data#63]
Hi-

Using Rails 3, Gem version 1.1.10.

Noticed a routing error on app/views/admin_data/search/search/_listing.html.erb:27:
    No route matches {:controller=>"admin_data/public", :action=>"serve", :klass=>"role", :id=>#<Role id: 930089099, name: "Admin"...

This happens where you're calling 
    <%= link_to(record.to_param.to_s, admin_data_path(:klass => klass.name.underscore, :id => record)) %>

Traced this back to the routes, it seems that you've duplicated the admin_data_path (from 'rake routes'):

```
admin_data GET    /admin_data/klass/:klass/:id(.:format)           {:controller=>"admin_data/crud", :action=>"show"}
admin_data        /admin_data/public/*file(.:format)               {:controller=>"admin_data/public", :action=>"serve"}
```

So it's trying to use the admin_data/public controller instead of admin_data/crud.  In the routes when I give the public route a new name then it works:

```
match '/public/*file' => "public#serve", :as => :public
```

I'll probably fork and send a pull request, but I wanted to also submit this as an issue.  Apologies if it's a duplicate.  Hope this makes sense.

**Comment by neerajsingh0101** [comment]
fixed as per https://github.com/neerajdotname/admin_data/commit/a2f1dc8d5996689037a83813eaecc83ec092434f
