### ISSUE TITLE
issues with routes on rails 3

### ISSUE THREAD

**Issue by carlshimer** [neerajsingh0101/admin_data#69]
I can't get the stock gem routes to work with public/stylesheets/base.css public/images/*.png

I can't tell why it doesn't work from looking at the source.  My hack work around:

module AdminData
  class PublicController < ApplicationController
    def stylesheets
      path = File.join(AdminData::LIBPATH, 'public', 'stylesheets',"#{params[:id]}.css")
      render({:text => File.read(path), :cache => true, :content_type => "text/css"})
    end
    def images
      path = File.join(AdminData::LIBPATH, 'public', 'images',"#{params[:id]}.png")
      render({:text => File.read(path), :cache => true, :content_type => "image/png"})
    end
  end
end

**Comment by neerajsingh0101** [comment]
That's weird. 

Well  if you find out the reason why it is not working and if you think code needs to change then let me know.

Thanks

**Comment by neerajsingh0101** [comment]
Having a catch all route might break a lot of things in admin_data. It is strongly recommended to not to use catch-all route.

```
# keep this line commented in your routes file
# match '/:controller(/:action(/:id))'
```

**Comment by neerajsingh0101** [comment]
That's a great solution. I can recommend this solution to others too. 

Thanks for sharing.
