### ISSUE TITLE
Hide certain columns

### ISSUE THREAD

**Issue by avishai** [neerajsingh0101/admin_data#7]
You should be able to exclude certain columns from the view, both in the listing and the detail page of a record.

Many apps/models have columns which aren't at all useful outside of the code, like crypted_password, salt, etc.

**Comment by neerajsingh0101** [comment]
Now you can changer the order of columns in the listing. Hope that helps.

http://neerajdotname.github.com/admin_data/#custom_order_of_columns

Closing this issue.

**Comment by pogermano** [comment]
Is it possible? I'm using rails 2.3.8. Thanks!

**Comment by neerajsingh0101** [comment]
@pogermano Honestly I do not know. I have not looked at 2.3.8 code in months.
