### ISSUE TITLE
admin_data shows deprecated warning

### ISSUE THREAD

**Issue by rdp** [neerajsingh0101/admin_data#71]
Since there's no mailing list to mention this on, here it is :)

DEPRECATION WARNING: Rake tasks in vendor/plugins/admin_data/tasks and vendor/plugins/admin_data/tasks are deprecated. Use lib/tasks instead. (called from C:/dev/ruby/musicformormons/vendor/rails/railties/lib/tasks/rails.rb:10)

**Comment by neerajsingh0101** [comment]
what version of rails you are using?

**Comment by rdp** [comment]
2.3.8

**Comment by neerajsingh0101** [comment]
If you use rails3 then this problem is fixed there.
