### ISSUE TITLE
feature request: edit fields in the same order as show fields

### ISSUE THREAD

**Issue by rdp** [neerajsingh0101/admin_data#72]
Hello.
I noticed that the edit page doesn't obey the "columns_order" ordering. Might be nice to.
Thanks!
-r

**Comment by neerajsingh0101** [comment]
what version of rails you are using?

**Comment by rdp** [comment]
2.3.something

**Comment by neerajsingh0101** [comment]
That's an older version of admin_data. If you experience same problem with rails3 and the latest version of gem then I will take a look.
