### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by kulpreet** [neerajsingh0101/admin_data#8]
Click on condition after selecting a boolean column, results in a JS exception

From firebug - 

AdminDataJSUtil.column_options[col1_type] is undefined
[Break on this error] var options = AdminDataJSUtil.column_options[col1_type]['options'];\n

There is no exception if the boolean column is selected as a second row. But it shows no conditions in the conditions drop down.

Other column types work. This is on postgres, just in case it matters.

**Comment by neerajsingh0101** [comment]
Well that gives me a perfect excuse to write test for JavaScript. I will work on it. Thanks for reporting.

**Comment by kulpreet** [comment]
Found the problem. There is a typo in adv_search.js L219. 

The options are set for booleant instead of boolean. Therer's an extra 't'. Hope that helps.

**Comment by neerajsingh0101** [comment]
Try now. It should be fixed. Thanks for pointing out the bug.

This commit fixes it. http://github.com/neerajdotname/admin_data/commit/b2f04486755a73587485d428d4016423df3779f6

**Comment by neerajsingh0101** [comment]
Closing this issue
