### ISSUE TITLE
Heroku Application appears to be down

### ISSUE THREAD

**Issue by kellydunn** [neerajsingh0101/admin_data#96]
Hello there! 

Upon first glance, the `admin_data` project looks very compelling!  I would love to integrate something like this into some of the projects I work on, but I'm unfortunately unable to demo the funcitonality;  the link on the main github page is resulting in an "no such app" error:

http://admin-data-demo.heroku.com/admin_data

Has the heroku configuration changed as of late?  Would love to try this out before integrating into my projects :)

**Comment by neerajsingh0101** [comment]
@kellydunn We are building a brand new version of admin_data which is much more leaner and will have less features. 

In the new version admin_data will have `read only` functionality. 

We expect this feature to be live by the end of March. So please check back in a few weeks. Thanks.

**Comment by kellydunn** [comment]
Sounds great!  Is there anyway to check out the current functionality?  Or is the new feature set diverged far enough that it's not worth reviving the heroku application at this point in time?  

Are there prescribed branches or tags that third party developers should clone or fork from in the meantime?

**Comment by neerajsingh0101** [comment]
@kellydunn Given that amount of change that is happening right now I would say third party developers should wait for the next release. In the next release we will update the readme and will also update the demo site .

**Comment by kellydunn** [comment]
Thanks for the swift and thoughtful response :)

In the interim, it might be worth it to update the README so that developers don't misinterpret the project as "broken" or otherwise abandoned.

For all intents and purposes, I'll consider this issue is closed.
